// data.js
// ئەم فایلە تەنها بۆ هەڵگرتنی داتای فەرهەنگەکە بەکاردێت.
// پێویستە لە index.html پێش script.js بار بکرێت.

const dictionaryData = {
    english: {
        "a": { sorani: "ئ", hawrami: "ئا", arabic: "أ" },
        "about": { sorani: "دەربارە", hawrami: "دەربارە", arabic: "عن" },
        "hello": { sorani: "سڵاو", hawrami: "ڕاسیە", arabic: "مرحباً" },
        "yes": { sorani: "بەڵێ", hawrami: "ئەرێ", arabic: "نعم" },
        "green": { sorani: "سەوز", hawrami: "کەو", arabic: "أخضر" },
        "zoo": { sorani: "باخچەی ئاژەڵان", hawrami: "باخەلی گیانەوەران", arabic: "حديقة حيوان" },
        "green light": { sorani: "چرا سەوز", hawrami: "ڕوشنایی کەو", arabic: "ضوء أخضر" },
        "book": { sorani: "کتێب", hawrami: "کتاو", arabic: "كتاب" },
        "computer": { sorani: "کۆمپیوتەر", hawrami: "کۆمپیتەر", arabic: "حاسوب" },
        "water": { sorani: "ئاو", hawrami: "ئاو", arabic: "ماء" },
        "red": { sorani: "سوور", hawrami: "سۆر", arabic: "أحمر" },
        "blue": { sorani: "شین", hawrami: "کەو", arabic: "أزرق" },
        "yellow": { sorani: "زەرد", hawrami: "زەرد", arabic: "أصفر" },
        "apple": { sorani: "سێو", hawrami: "سەو", arabic: "تفاح" },
        "orange": { sorani: "پرتەقاڵ", hawrami: "پرتەقاڵ", arabic: "برتقال" },
        "grape": { sorani: "ترێ", hawrami: "ترێ", arabic: "عنب" },
        "flower": { sorani: "گوڵ", hawrami: "وەرێ", arabic: "زهرة" },
        "tree": { sorani: "درەخت", hawrami: "دار", arabic: "شجرة" },
        "house": { sorani: "ماڵ", hawrami: "ماڵ", arabic: "منزل" },
        "car": { sorani: "ئۆتۆمبێل", hawrami: "ئۆتۆمۆبیل", arabic: "سيارة" },
        "road": { sorani: "ڕێگا", hawrami: "ڕێگا", arabic: "طريق" },
        "mountain": { sorani: "چیا", hawrami: "کێو", arabic: "جبل" },
        "river": { sorani: "ڕووبار", hawrami: "ڕووبار", arabic: "نهر" },
        "city": { sorani: "شار", hawrami: "شار", arabic: "مدينة" },
        "village": { sorani: "گوند", hawrami: "گوند", arabic: "قرية" },
        "school": { sorani: "قوتابخانە", hawrami: "قوتابخانە", arabic: "مدرسة" },
        "student": { sorani: "قوتابی", hawrami: "قوتابی", arabic: "طالب" },
        "teacher": { sorani: "مامۆستا", hawrami: "مامۆستا", arabic: "معلم" },
        "doctor": { sorani: "پزیشک", hawrami: "پزیشک", arabic: "طبيب" },
        "nurse": { sorani: "پەرستار", hawrami: "پەرستار", arabic: "ممرض" },
        "hospital": { sorani: "نەخۆشخانە", hawrami: "نەخۆشخانە", arabic: "مستشفى" },
        "food": { sorani: "خواردن", hawrami: "خواردن", arabic: "طعام" },
        "drink": { sorani: "خواردنەوە", hawrami: "شۆربە", arabic: "شراب" },
        "morning": { sorani: "بەیانی", hawrami: "سەرۆ", arabic: "صباح" },
        "evening": { sorani: "ئێوارە", hawrami: "ئێوارە", arabic: "مساء" },
        "night": { sorani: "شەو", hawrami: "شەو", arabic: "ليل" },
        "day": { sorani: "ڕۆژ", hawrami: "ڕۆژ", arabic: "يوم" },
        "week": { sorani: "هەفتە", hawrami: "هەفتە", arabic: "أسبوع" },
        "month": { sorani: "مانگ", hawrami: "مانگ", arabic: "شهر" },
        "year": { sorani: "ساڵ", hawrami: "ساڵ", arabic: "سنة" },
        "time": { sorani: "کات", hawrami: "وەخت", arabic: "وقت" }
    },
    sorani: {
        "ئ": { english: "a", hawrami: "ئا", arabic: "أ" },
        "دەربارە": { english: "about", hawrami: "دەربارە", arabic: "عن" },
        "سڵاو": { english: "hello", hawrami: "ڕاسیە", arabic: "مرحباً" },
        "بەڵێ": { english: "yes", hawrami: "ئەرێ", arabic: "نعم" },
        "سەوز": { english: "green", hawrami: "کەو", arabic: "أخضر" },
        "باخچەی ئاژەڵان": { english: "zoo", hawrami: "باخەلی گیانەوەران", arabic: "حديقة حيوان" },
        "چرا سەوز": { english: "green light", hawrami: "ڕوشنایی کەو", arabic: "ضوء أخضر" },
        "کتێب": { english: "book", hawrami: "کتاو", arabic: "كتاب" },
        "کۆمپیوتەر": { english: "computer", hawrami: "کۆمپیتەر", arabic: "حاسوب" },
        "ئاو": { english: "water", hawrami: "ئاو", arabic: "ماء" },
        "سوور": { english: "red", hawrami: "سۆر", arabic: "أحمر" },
        "شین": { english: "blue", hawrami: "کەو", arabic: "أزرق" },
        "زەرد": { english: "yellow", hawrami: "زەرد", arabic: "أصفر" },
        "سێو": { english: "apple", hawrami: "سەو", arabic: "تفاح" },
        "پرتەقاڵ": { english: "orange", hawrami: "پرتەقاڵ", arabic: "برتقال" },
        "ترێ": { english: "grape", hawrami: "ترێ", arabic: "عنب" },
        "گوڵ": { english: "flower", hawrami: "وەرێ", arabic: "زهرة" },
        "درەخت": { english: "tree", hawrami: "دار", arabic: "شجرة" },
        "ماڵ": { english: "house", hawrami: "ماڵ", arabic: "منزل" },
        "ئۆتۆمبێل": { english: "car", hawrami: "ئۆتۆمۆبیل", arabic: "سيارة" },
        "ڕێگا": { english: "road", hawrami: "ڕێگا", arabic: "طريق" },
        "چیا": { english: "mountain", hawrami: "کێو", arabic: "جبل" },
        "ڕووبار": { english: "river", hawrami: "ڕووبار", arabic: "نهر" },
        "شار": { english: "city", hawrami: "شار", arabic: "مدينة" },
        "گوند": { english: "village", hawrami: "گوند", arabic: "قرية" },
        "قوتابخانە": { english: "school", hawrami: "قوتابخانە", arabic: "مدرسة" },
        "قوتابی": { english: "student", hawrami: "قوتابی", arabic: "طالب" },
        "مامۆستا": { english: "teacher", hawrami: "مامۆستا", arabic: "معلم" },
        "پزیشک": { english: "doctor", hawrami: "پزیشک", arabic: "طبيب" },
        "پەرستار": { english: "nurse", hawrami: "پەرستار", arabic: "ممرض" },
        "نەخۆشخانە": { english: "hospital", hawrami: "نەخۆشخانە", arabic: "مستشفى" },
        "خواردن": { english: "food", hawrami: "خواردن", arabic: "طعام" },
        "خواردنەوە": { english: "drink", hawrami: "شۆربە", arabic: "شراب" },
        "بەیانی": { english: "morning", hawrami: "سەرۆ", arabic: "صباح" },
        "ئێوارە": { english: "evening", hawrami: "ئێوارە", arabic: "مساء" },
        "شەو": { english: "night", hawrami: "شەو", arabic: "ليل" },
        "ڕۆژ": { english: "day", hawrami: "ڕۆژ", arabic: "يوم" },
        "هەفتە": { english: "week", hawrami: "هەفتە", arabic: "أسبوع" },
        "مانگ": { english: "month", hawrami: "مانگ", arabic: "شهر" },
        "ساڵ": { english: "year", hawrami: "ساڵ", arabic: "سنة" },
        "کات": { english: "time", hawrami: "وەخت", arabic: "وقت" }
    },
    hawrami: {
        "ئا": { english: "a", sorani: "ئ", arabic: "أ" },
        "دەربارە": { english: "about", sorani: "دەربارە", arabic: "عن" },
        "ڕاسیە": { english: "hello", sorani: "سڵاو", arabic: "مرحباً" },
        "ئەرێ": { english: "yes", sorani: "بەڵێ", arabic: "نعم" },
        "کەو": { english: "green", sorani: "سەوز", arabic: "أخضر" },
        "باخەلی گیانەوەران": { english: "zoo", sorani: "باخچەی ئاژەڵان", arabic: "حديقة حيوان" },
        "ڕوشنایی کەو": { english: "green light", sorani: "چرا سەوز", arabic: "ضوء أخضر" },
        "کتاو": { english: "book", sorani: "کتێب", arabic: "كتاب" },
        "کۆمپیتەر": { english: "computer", sorani: "کۆمپیوتەر", arabic: "حاسوب" },
        "ئاو": { english: "water", sorani: "ئاو", arabic: "ماء" },
        "سۆر": { english: "red", sorani: "سوور", arabic: "أحمر" },
        "شین": { english: "blue", sorani: "شین", arabic: "أزرق" },
        "زەرد": { english: "yellow", sorani: "زەرد", arabic: "أصفر" },
        "سەو": { english: "apple", sorani: "سێو", arabic: "تفاح" },
        "پرتەقاڵ": { english: "orange", sorani: "پرتەقاڵ", arabic: "برتقال" },
        "ترێ": { english: "grape", sorani: "ترێ", arabic: "عنب" },
        "وەرێ": { english: "flower", sorani: "گوڵ", arabic: "زهرة" },
        "دار": { english: "tree", sorani: "درەخت", arabic: "شجرة" },
        "ماڵ": { english: "house", sorani: "ماڵ", arabic: "منزل" },
        "ئۆتۆمۆبیل": { english: "car", sorani: "ئۆتۆمبێل", arabic: "سيارة" },
        "ڕێگا": { english: "road", sorani: "ڕێگا", arabic: "طريق" },
        "کێو": { english: "mountain", sorani: "چیا", arabic: "جبل" },
        "ڕووبار": { english: "river", sorani: "ڕووبار", arabic: "نهر" },
        "شار": { english: "city", sorani: "شار", arabic: "مدينة" },
        "گوند": { english: "village", sorani: "گوند", arabic: "قرية" },
        "قوتابخانە": { english: "school", sorani: "قوتابخانە", arabic: "مدرسة" },
        "قوتابی": { english: "student", hawrami: "قوتابی", arabic: "طالب" },
        "مامۆستا": { english: "teacher", sorani: "مامۆستا", arabic: "معلم" },
        "پزیشک": { english: "doctor", sorani: "پزیشک", arabic: "طبيب" },
        "پەرستار": { english: "nurse", sorani: "پەرستار", arabic: "ممرض" },
        "نەخۆشخانە": { english: "hospital", sorani: "نەخۆشخانە", arabic: "مستشفى" },
        "خواردن": { english: "food", sorani: "خواردن", arabic: "طعام" },
        "شۆربە": { english: "drink", sorani: "خواردنەوە", arabic: "شراب" },
        "سەرۆ": { english: "morning", sorani: "بەیانی", arabic: "صباح" },
        "ئێوارە": { english: "evening", sorani: "ئێوارە", arabic: "مساء" },
        "شەو": { english: "night", sorani: "شەو", arabic: "ليل" },
        "ڕۆژ": { english: "day", sorani: "ڕۆژ", arabic: "يوم" },
        "هەفتە": { english: "week", sorani: "هەفتە", arabic: "أسبوع" },
        "مانگ": { english: "month", sorani: "مانگ", arabic: "شهر" },
        "ساڵ": { english: "year", sorani: "ساڵ", arabic: "سنة" },
        "وەخت": { english: "time", sorani: "کات", arabic: "وقت" }
    },
    arabic: {
        "أ": { english: "a", sorani: "ئ", hawrami: "ئا" },
        "عن": { english: "about", sorani: "دەربارە", hawrami: "دەربارە" },
        "مرحباً": { english: "hello", sorani: "سڵاو", hawrami: "ڕاسیە" },
        "نعم": { english: "yes", sorani: "بەڵێ", hawrami: "ئەرێ" },
        "أخضر": { english: "green", sorani: "سەوز", hawrami: "کەو" },
        "حديقة حيوان": { english: "zoo", sorani: "باخچەی ئاژەڵان", hawrami: "باخەلی گیانەوەران" },
        "ضوء أخضر": { english: "green light", sorani: "چرا سەوز", hawrami: "ڕوشنایی کەو" },
        "كتاب": { english: "book", sorani: "کتێب", hawrami: "کتاو" },
        "حاسوب": { english: "computer", sorani: "کۆمپیوتەر", hawrami: "کۆمپیتەر" },
        "ماء": { english: "water", sorani: "ئاو", hawrami: "ئاو" },
        "أحمر": { english: "red", sorani: "سوور", hawrami: "سۆر" },
        "أزرق": { english: "blue", sorani: "شین", hawrami: "کەو" },
        "أصفر": { english: "yellow", sorani: "زەرد", hawrami: "زەرد" },
        "تفاح": { english: "apple", sorani: "سێو", hawrami: "سەو" },
        "برتقال": { english: "orange", sorani: "پرتەقاڵ", hawrami: "پرتەقاڵ" },
        "عنب": { english: "grape", sorani: "ترێ", hawrami: "ترێ" },
        "زهرة": { english: "flower", sorani: "گوڵ", hawrami: "وەرێ" },
        "شجرة": { english: "tree", sorani: "درەخت", hawrami: "دار" },
        "منزل": { english: "house", sorani: "ماڵ", hawrami: "ماڵ" },
        "سيارة": { english: "car", sorani: "ئۆتۆمبێل", hawrami: "ئۆتۆمۆبیل" },
        "طريق": { english: "road", sorani: "ڕێگا", hawrami: "ڕێگا" },
        "جبل": { english: "mountain", sorani: "چیا", hawrami: "کێو" },
        "نهر": { english: "river", sorani: "ڕووبار", hawrami: "ڕووبار" },
        "مدينة": { english: "city", sorani: "شار", hawrami: "شار" },
        "قرية": { english: "village", sorani: "گوند", hawrami: "گوند" },
        "مدرسة": { english: "school", sorani: "قوتابخانە", hawrami: "مدرسة" },
        "طالب": { english: "student", sorani: "قوتابی", hawrami: "طالب" },
        "معلم": { english: "teacher", sorani: "مامۆستا", hawrami: "مامۆستا" },
        "طبيب": { english: "doctor", sorani: "پزیشک", hawrami: "پزیشک" },
        "ممرض": { english: "nurse", sorani: "پەرستار", hawrami: "ممرض" },
        "مستشفى": { english: "hospital", sorani: "نەخۆشخانە", hawrami: "نەخۆشخانە" },
        "طعام": { english: "food", sorani: "خواردن", hawrami: "خواردن" },
        "شراب": { english: "drink", sorani: "خواردنەوە", hawrami: "شۆربە" },
        "صباح": { english: "morning", sorani: "بەیانی", hawrami: "سەرۆ" },
        "مساء": { english: "evening", sorani: "ئێوارە", hawrami: "ئێوارە" },
        "ليل": { english: "night", sorani: "شەو", hawrami: "شەو" },
        "يوم": { english: "day", sorani: "ڕۆژ", hawrami: "ڕۆژ" },
        "أسبوع": { english: "week", sorani: "هەفتە", arabic: "أسبوع" },
        "شهر": { english: "month", sorani: "مانگ", arabic: "شهر" },
        "سنة": { english: "year", sorani: "ساڵ", arabic: "سنة" },
        "وقت": { english: "time", sorani: "کات", arabic: "وقت" }
    }
};